id: PED11418A
initial_creation_type: ocr
source_metadata:
  volumes:
    072d857f55ae43a7b02fe669080a182a:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: གནས་ཆེན་པོ་བརྒྱད་ཀྱི་མཆོད་རྟེན་ལ་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
